"""Optional Features but allow null for priority

Revision ID: 78262f9768a7
Revises: c8ca94880348
Create Date: 2025-04-05 14:44:57.308455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78262f9768a7"
down_revision: Union[str, None] = "c8ca94880348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "priority", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "priority", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
