"""Optional Features

Revision ID: c8ca94880348
Revises: 63c5b0a75068
Create Date: 2025-04-05 14:04:28.697361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ca94880348'
down_revision: Union[str, None] = '63c5b0a75068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('todos', sa.Column('priority', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_todos_due_date'), 'todos', ['due_date'], unique=False)
    op.create_index(op.f('ix_todos_priority'), 'todos', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_priority'), table_name='todos')
    op.drop_index(op.f('ix_todos_due_date'), table_name='todos')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
