name: Run Python Tests
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dummy .env file for config
        run: |
          echo "SECRET_KEY=ci-dummy-test-secret-key-needs-to-be-long-enough" >> .env
          echo "ALGORITHM=HS256" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=5" >> .env
          echo "DATABASE_URL=postgresql+psycopg2://test:test@localhost:5432/testdb" >> .env
          echo "Created dummy .env file:"
          cat .env

      - name: Run tests with pytest
        run: |
          pytest -v 
